name: Node.js Package

on:
  push:
    branches: [main]
jobs:
  publish-gpr:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: 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
